version: '3'
services:
  api-libros:
    image: books-grupal-s
    environment:
      SERVER_PORT: 8081
      spring.data.mongodb.host: mongodb-service
    ports:
      - "8081:8081"
    depends_on:
      - mongodb-service
  mongodb-service:
    image: mongo:latest
    ports:
      - "27017:27017"